Repository DataFlowAnalysis/DataFlowAnalysis, pull requests merged in 2024-01, with the labels that each got.

#99 Add test and testmodel for unknown seff actions
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/.project
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.allocation
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.repository
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.resourceenvironment
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.system
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.usagemodel
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/dic.pddc
  tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/representations.aird
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/ConstraintFeatureTest.java
Labels: testing

#109 Fix typo for resource assignees
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/PCMNodeCharacteristicsCalculator.java
  tests/org.dataflowanalysis.analysis.testmodels/models/CompositeCharacteristicsTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/InternationalOnlineShop/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/NodeCharacteristicsTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/OneAssembyMultipleResourceContainerTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/TravelPlanner/travelPlanner.nodecharacteristics
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/ConstraintResultTest.java
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/data/ConstraintViolations.java
Labels: bug

#111 Add ids for all nodecharacteristics entries
  tests/org.dataflowanalysis.analysis.testmodels/models/CompositeCharacteristicsTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/InternationalOnlineShop/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/NodeCharacteristicsTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/OneAssembyMultipleResourceContainerTest/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/ReturnTestModel/default.nodecharacteristics
  tests/org.dataflowanalysis.analysis.testmodels/models/TravelPlanner/travelPlanner.nodecharacteristics
Labels: bug

#108 Remove analysis data from dfd analysis constructor
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDActionSequence.java
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/AbstractPCMActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/PCMActionSequence.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/CallingSEFFActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/SEFFActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/CallingUserActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/UserActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/AnalysisData.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/AbstractActionSequenceElement.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/ActionSequence.java
Labels: enhancement

#113 Change visibility in analysis and builder to enable inheritance.
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
Labels: enhancement

#122 Validate data in PCM Builder
  bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
Labels: bug, core
