Repository DataFlowAnalysis/DataFlowAnalysis, pull requests merged in 2025-07, with the labels that each got.

#313 Fix issues with parsing and evaluating vertex selectors
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexDestinationSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexSourceSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLNodeDestinationSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLNodeSourceSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicListSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsListSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/utils/ParseResult.java
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/DSLResultTest.java
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/VertexCharacteristicListSelectorTest.java
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/VertexSourceSelectorTest.java
Labels: bug, core

#315 Skip whitespace characters in DSL
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/ConditionalSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/DataSourceSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexDestinationSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexSourceSelectors.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/CharacteristicsSelectorData.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicListSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicsSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/EmptySetOperationConditionalSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/Intersection.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableConditionalSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableNameSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsListSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexTypeSelector.java
  bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/utils/StringView.java
  tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/SourceSelectorsTest.java
Labels: enhancement, core, support

#298 Converter update
  bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDVertex.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/dfd2web/DFD2WebConverter.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/ChildSerializer.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/Web2DFDConverter.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/model/Annotation.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/model/Child.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/model/Port.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/model/Position.java
  bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/web2dfd/model/Size.java
  pom.xml
  tests/org.dataflowanalysis.converter.tests/src/org/dataflowanalysis/converter/tests/AnnotationsTest.java
  tests/org.dataflowanalysis.converter.tests/src/org/dataflowanalysis/converter/tests/PCMTest.java
Labels: core, converter
